-- Q1 Which apps have the highest rating in the given available dataset?
SELECT App, 
		Rating 
FROM playstore_apps
ORDER BY Rating DESC
LIMIT 20;

-- Q2  What are the number of installs and reviews for the above apps? Return the apps with the highest reviews to the top.?
SELECT App, 
		Rating,
                Installs,
                Reviews
FROM playstore_apps
ORDER BY Reviews DESC
LIMIT 20;

-- Q3 Which app has the highest number of reviews? 
-- Also, mention the number of reviews and category of the app?
SELECT App, 
                Reviews,
                Category
FROM playstore_apps
ORDER BY Reviews DESC
LIMIT 20;

-- Q4 What is the total amount of revenue generated by the google play store by hosting apps? 
-- (Whenever a user buys apps  from the google play store, the amount is considered in the revenue)

SELECT SUM(Installs * Price) Total_Revenue
FROM playstore_apps;

-- Q5 Which Category of google play store apps has the highest number of installs?
-- also, find out the total number of installs for that particular category.

SELECT Category,
		Installs
FROM playstore_apps
GROUP BY Category
ORDER BY Installs DESC
LIMIT 3;

-- Q6 Which Genre has the most number of published apps?
SELECT Genres,
		COUNT(*) Number_Of_Apps
FROM playstore_apps
GROUP BY Genres
ORDER BY 2 DESC
LIMIT 3;

-- Q7 Provide the list of all games ordered in such a way that the game that has 
-- the highest number of installs is displayed on the top(to avoid duplicate results use distinct)
SELECT App,
		Installs
FROM playstore_apps
ORDER BY Installs DESC
LIMIT 10;
-- Note::: I already removed the duplicates when I noticed them on Excel; Criteria was Apps with same name, size, rating, price & genre


-- Q8 Provide the list of apps that can work on android version 4.0.3 and UP.?
SELECT App,
		`Android Ver`
FROM playstore_apps
WHERE `Android Ver` >= '4.0.3 and up';

-- Q9 How many apps from the given data set are free? Also, provide the number of paid apps.?
SELECT Type,
		COUNT(*) Count
FROM playstore_apps
GROUP BY Type;

-- Q10 Which is the best dating app? (Best dating app is the one having the highest number of Reviews)
SELECT App,
		Category,
                Reviews
FROM playstore_apps
WHERE Category = 'DATING'
LIMIT 1;

-- Q11 Get the number of reviews having positive sentiment and number of reviews
--  having negative sentiment for the app 10 best foods for you and compare them.
SELECT App,
		Sentiment,
                COUNT(*) Sentiment_Count
FROM playstore_reviews
WHERE App = '10 Best Foods for You' 
GROUP BY Sentiment;

-- Q12 Which comments of ASUS SuperNote have sentiment polarity and sentiment subjectivity both as 1?
SELECT *
FROM playstore_reviews
WHERE App = 'ASUS SuperNote' AND Sentiment_Polarity = 1 AND Sentiment_Subjectivity = 1;

-- Q13 Get all the neutral sentiment reviews for the app Abs Training-Burn belly fat ?
SELECT *
FROM playstore_reviews
WHERE App = 'Abs Training-Burn belly fat' AND Sentiment = 'Neutral';

-- Q14 Extract all negative sentiment reviews for 
-- Adobe Acrobat Reader with their sentiment polarity and sentiment subjectivity?
SELECT *
FROM playstore_reviews
WHERE App = 'Adobe Acrobat Reader' AND Sentiment = 'Negative';